trigger:
- doc-source

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: github

steps:
- task: UseNode@1
  inputs:
    version: '12.x'
    checkLatest: true

- task: CmdLine@2
  inputs:
    script: |
      sudo timedatectl set-timezone Asia/Shanghai
      yarn install --pure-lockfile
      yarn docs:build
      cd 'docs/.vuepress/dist'
      touch .nojekyll
      git config --global user.email "$(EMAIL)"
      git config --global user.name "$(USER)"
      git init
      git add .
      git commit -m update
      git push --force --quiet https://$(TOKEN)@github.com/MonoLogueChi/Danmu.Server.git master:gh-pages
