title: 弹幕服务器文档
description: Danmu.Server 弹幕服务器文档
theme: thindark
base: /
head:
  - type: link
    rel: icon
    href: /favicon.png

themeConfig:
  sidebarDepth: 2
  smoothScroll: true
  nav:
    弹幕服务器:
      简介: /danmu/
      编译: /danmu/make.html
      安装: /danmu/install.html
      管理: /danmu/admin.html
      API: /danmu/api.html
    直播弹幕服务器:
      简介: /live/
      安装: /live/install.html
      API: /live/api.html
    其他相关文档:
      其他文档: /other/
      PostgreSQL安装: /other/pgsql.html
      FQA: /other/fqa.html
      感谢: /other/sponsors.html
  sidebar:
    /danmu/:
      - make
      - install
      - admin
      - api
    /live/:
      - install
      - api
    /other/:
      - pgsql
      - fqa
      - sponsors
  repo: MonoLogueChi/Danmu.Server
  repoLabel: GitHub
  docsDir: docs
  docsBranch: doc-source
  editLinks: true
  editLinkText: 在 GitHub 上编辑此页
