KestrelSettings:
  Port:
    - 5000
  UnixSocketPath:
    - "/tmp/danmu.sock"
WithOrigins:
  - "*"
LiveWithOrigins:
  - http://localhost
  - http://localhost:4000
  - https://doc.video.xwhite.studio
AdminWithOrigins:
  - http://localhost:5000
DanmuSql:
  Sql: 0
  Host: 127.0.0.1
  Port: 0
  UserName: danmaku
  PassWord: danmaku
  DataBase: danmaku
  PoolSize: 16
Admin:
  User: MonoLogueChi
  Password: "000000"
  MaxAge: 60
BiliBiliSetting:
  Cookie: ""
  CidCacheTime: 168
  DanmuCacheTime: 12
